name: Publish Package

on:
  push:
    tags:
    - 'v*'


jobs:
  release:
    name: Publish to Github Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://npm.pkg.github.com'
      - name: Versions
        run: |
          node --version
          npm --version
      - name: Dependencies
        run: |
          npm install
      - name: Test
        run: |
          npm run test
      - name: Compile
        run: |
          npm run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
