name: Test PRs to Trunk

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run Tests
        run: |
          npm install
          npm run test
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
